name: Recover Secret Securely
on: workflow_dispatch # Allows you to trigger this manually

jobs:
  recover:
    runs-on: ubuntu-latest
    environment: database-creation # Match your target environment
    
    steps:
      - name: Encrypt and Save Secret
        env:
          # Replace with your actual secret name
          APP_RUNTIME_PASSWORD: ${{ secrets.APP_RUNTIME_PASSWORD }} 
          MIGRATION_RUNNER_PASSWORD: ${{ secrets.MIGRATION_RUNNER_PASSWORD }} 

          # Choose a temporary strong password to lock the zip file
          ZIP_PASS: "6iHPC4yfaWm6kkD3NKaT5GzPL9U" 
        run: |
          # 1. Write the plain text to a local runner file (safe, runner destroys itself later)
          echo $APP_RUNTIME_PASSWORD >> plain_secret.txt
          echo $MIGRATION_RUNNER_PASSWORD >> plain_secret.txt
          
          # 2. Securely zip and encrypt the file using a password
          zip -P "$ZIP_PASS" encrypted_secret.zip plain_secret.txt
          
      - name: Upload Secret as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: secure-secret-drop
          path: encrypted_secret.zip
          retention-days: 1 # Automatically deletes quickly
